"""
Certificate Generation - PDF Creation
"""

from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.utils import ImageReader
from datetime import datetime
import os
from PIL import Image

def generate_certificate(student_name, event_title, event_date, organizer_name, output_path, prize_text=None):
    """
    Generate PDF certificate for event attendance
    
    Args:
        student_name: Name of the student
        event_title: Title of the event
        event_date: Date of the event
        organizer_name: Name of the organizer
        output_path: Path to save the PDF
        prize_text: Optional prize/position text (e.g., "1st Place - Winner")
    """
    # Create PDF in landscape mode
    c = canvas.Canvas(output_path, pagesize=landscape(letter))
    width, height = landscape(letter)

    # Ensure output directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # Colors
    primary = colors.HexColor('#0b3d91')
    accent = colors.HexColor('#f59e0b')
    text = colors.HexColor('#1f2937')
    gold = colors.HexColor('#d97706')

    # Background border
    c.setStrokeColor(primary)
    c.setLineWidth(4)
    c.roundRect(0.4*inch, 0.4*inch, width-0.8*inch, height-0.8*inch, 12, stroke=1, fill=0)

    # Decorative header bar
    c.setFillColor(primary)
    c.rect(0.4*inch, height-1.05*inch, width-0.8*inch, 0.6*inch, stroke=0, fill=1)

    # College name
    c.setFillColor(colors.white)
    c.setFont('Helvetica-Bold', 18)
    c.drawCentredString(width/2, height-0.7*inch, 'COLLEGE OF ENGINEERING THALASSERY')

    # Large certificate title
    c.setFillColor(primary)
    c.setFont('Times-Bold', 34)
    if prize_text:
        c.drawCentredString(width/2, height-1.55*inch, 'Certificate of Achievement')
    else:
        c.drawCentredString(width/2, height-1.6*inch, 'Certificate of Participation')

    # Prize badge if present
    if prize_text:
        # Draw gold prize banner
        c.setFillColor(gold)
        c.setFont('Helvetica-Bold', 16)
        c.drawCentredString(width/2, height-2.0*inch, f'🏆 {prize_text} 🏆')

    # Subtitle
    c.setFont('Helvetica', 12)
    c.setFillColor(text)
    subtitle_y = height-2.35*inch if prize_text else height-2.05*inch
    c.drawCentredString(width/2, subtitle_y, 'This is to certify that')

    # Student name
    c.setFont('Times-BoldItalic', 30)
    c.setFillColor(primary)
    name_y = height-2.9*inch if prize_text else height-2.65*inch
    c.drawCentredString(width/2, name_y, student_name)

    # Participated in
    c.setFont('Helvetica', 12)
    c.setFillColor(text)
    participated_y = height-3.35*inch if prize_text else height-3.15*inch
    c.drawCentredString(width/2, participated_y, 'has successfully participated in')

    # Event title (wrapped if long)
    c.setFont('Helvetica-Bold', 18)
    c.setFillColor(accent)
    max_width = width - 3*inch
    event_title_y = height-3.8*inch if prize_text else height-3.6*inch
    # Simple wrap
    if c.stringWidth(event_title, 'Helvetica-Bold', 18) > max_width:
        words = event_title.split()
        mid = len(words)//2
        line1 = ' '.join(words[:mid])
        line2 = ' '.join(words[mid:])
        c.drawCentredString(width/2, event_title_y, line1)
        c.drawCentredString(width/2, event_title_y - 0.4*inch, line2)
        event_y = event_title_y - 0.9*inch
    else:
        c.drawCentredString(width/2, event_title_y, event_title)
        event_y = event_title_y - 0.4*inch

    # Event date
    c.setFont('Helvetica', 12)
    c.setFillColor(text)
    try:
        c.drawCentredString(width/2, event_y, f"Held on: {event_date}")
    except Exception:
        c.drawCentredString(width/2, event_y, f"Date: {event_date}")

    # (Watermark removed per user request)

    # Signature area
    sig_x = width - 3.5*inch
    sig_y = 1.9*inch
    c.setStrokeColor(text)
    c.line(sig_x-0.2*inch, sig_y, sig_x+2.4*inch, sig_y)
    c.setFont('Helvetica-Bold', 12)
    c.setFillColor(text)
    c.drawCentredString(sig_x+1.1*inch, sig_y-0.3*inch, organizer_name)
    c.setFont('Helvetica', 10)
    c.drawCentredString(sig_x+1.1*inch, sig_y-0.6*inch, 'Event Organizer')

    # Issue date bottom-left
    c.setFont('Helvetica', 10)
    c.setFillColor(text)
    c.drawString(0.7*inch, 1.1*inch, f"Issued: {datetime.now().strftime('%B %d, %Y')}")

    # Footer
    c.setFont('Helvetica-Oblique', 9)
    c.setFillColor(colors.HexColor('#6b7280'))
    c.drawCentredString(width/2, 0.7*inch, "Generated by Campus Event Management System - College of Engineering Thalassery")

    c.save()
    return output_path


def generate_certificate_with_template(
    student_name,
    event_title,
    event_date,
    organizer_name,
    output_path,
    template_path,
    positions=None,
    prize_text=None
):
    """Generate a certificate PDF using a custom background template image."""
    positions = positions or {}

    # Load template image and set page size to its dimensions
    img = Image.open(template_path)
    width, height = img.size
    img_reader = ImageReader(img)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    c = canvas.Canvas(output_path, pagesize=(width, height))

    # Draw background template
    c.drawImage(img_reader, 0, 0, width=width, height=height, mask='auto')

    # Default positions (percentages from top-left)
    defaults = {
        'student_name': {'x': 0.5, 'y': 0.42},
        'event_title': {'x': 0.5, 'y': 0.52},
        'event_date': {'x': 0.5, 'y': 0.60},
        'organizer_name': {'x': 0.75, 'y': 0.80},
        'issue_date': {'x': 0.15, 'y': 0.80},
        'prize_text': {'x': 0.5, 'y': 0.35}
    }

    # Default styles
    default_styles = {
        'student_name': {'font_size': 30, 'color': '#111827', 'bold': True, 'font': 'Times-Roman'},
        'event_title': {'font_size': 18, 'color': '#111827', 'bold': True, 'font': 'Times-Roman'},
        'event_date': {'font_size': 12, 'color': '#111827', 'bold': False, 'font': 'Helvetica'},
        'organizer_name': {'font_size': 12, 'color': '#111827', 'bold': True, 'font': 'Helvetica'},
        'issue_date': {'font_size': 10, 'color': '#111827', 'bold': False, 'font': 'Helvetica'},
        'prize_text': {'font_size': 16, 'color': '#d97706', 'bold': True, 'font': 'Helvetica'}
    }

    def _pos(field_key):
        pos = positions.get(field_key) or {}
        base = defaults.get(field_key, {'x': 0.5, 'y': 0.5})
        x_val = pos.get('x', base['x'])
        y_val = pos.get('y', base['y'])
        x = (x_val if x_val is not None else base['x']) * width
        y_top = (y_val if y_val is not None else base['y']) * height
        return x, (height - y_top)

    def _style(field_key):
        style = (positions.get(field_key) or {}).get('style') or {}
        base = default_styles.get(field_key, {'font_size': 12, 'color': '#111827', 'bold': False, 'font': 'Helvetica'})
        raw_size = style.get('font_size', base['font_size'])
        try:
            font_size = int(raw_size)
        except Exception:
            font_size = base['font_size']
        color = style.get('color', base['color'])
        bold = style.get('bold', base['bold'])
        font_family = style.get('font', base['font'])
        if font_family == 'Times-Roman':
            font_name = 'Times-Bold' if bold else 'Times-Roman'
        elif font_family == 'Courier':
            font_name = 'Courier-Bold' if bold else 'Courier'
        else:
            font_name = 'Helvetica-Bold' if bold else 'Helvetica'
        return font_name, font_size, color

    def _draw_centered(field_key, text):
        font_name, font_size, color = _style(field_key)
        c.setFillColor(colors.HexColor(color))
        c.setFont(font_name, font_size)
        x, y = _pos(field_key)
        c.drawCentredString(x, y, text)

    # Draw prize text first if present (appears above student name)
    if prize_text:
        _draw_centered('prize_text', f"🏆 {prize_text} 🏆")

    _draw_centered('student_name', student_name)
    _draw_centered('event_title', event_title)
    _draw_centered('event_date', event_date)
    _draw_centered('organizer_name', organizer_name)
    _draw_centered('issue_date', f"Issued: {datetime.now().strftime('%B %d, %Y')}")

    c.save()
    return output_path
